apiVersion: v1
kind: Service
metadata:
  name: randomapi-external-service  # Replace with your service name
spec:
  selector:
    app: randomapi-external # Replace with your pod selector label
  ports:
    - port: 8045          # Service port
      targetPort: 80  # Port on the pods the service will forward to
  type: LoadBalancer