apiVersion: v1
kind: Service
metadata:
  name: randomapi-external-service  # Replace with your service name
spec:
  selector:
    app: randomapi-external # در این قسمت مشخص میکنیم که چه پادهای با چه لبیلی را مدیریت کند
  ports:
    - port: 8045          # Service port
      targetPort: 80  # همان پورت کانینر که داخل پاد تعریف میکنیم 
  type: LoadBalancer