apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-randomapi-external
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/f/volumes-randomapi-external
    type: DirectoryOrCreate